name: CI

on:
  push:
    branches:
      - 'release'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "Installing dependencies and caching them."
          python -m pip install --upgrade pip
          pip install numpy pandas matplotlib
          pip install https://files.pythonhosted.org/packages/04/ea/49fd026ac36fdd79bf072294b139170aefc118e487ccb39af019946797e9/tensorflow-2.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install setuptools pytest pytest-cov parameterized
          pip install .
      - name:
        run: |
          ./shell/lint.sh
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest
